

export const userTypes = {
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
    SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
    SIGN_UP_FAIL:'SIGN_UP_FAIL',
    SIGN_IN_FAIL:"SIGN_IN_FAIL"
    

};