

export const userTypes = {
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
    SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
    SIGN_UP_FAIL:'SIGN_UP_FAIL',
    SIGN_IN_FAIL:"SIGN_IN_FAIL",
    PROFILE_UPDATE__FAIL:'PROFILE_UPDATE_FAIL',
    PROFILE_UPDATE_SUCCESS:'PROFILE_UPDATE_SUCCESS',
    STORE_PASSWORD:'STORE_PASSWOR',
    LOGOUT:"LOGOUT"
    

};

export const movieTypes = {
    ADD_MOVIES_SUCCESS:'ADD_MOVIES_SUCCRSS',
    EDIT_MOVIES_SUCCESS:'EDIT_MOVIES_SUCCRSS:',
    DELETE_MOVIES_SUCCESS:'DELETE_MOVIES_SUCCRSS',
    ADD_MOVIES_FAIL:'ADD_MOVIES_FAI',
    EDIT_MOVIES_FAIL:'EDIT_MOVIES_FAIL:',
    DELETEMOVIES_FAIL:'DELETEMOVIES_FAIL',
    GET_MOVIES_SUCCESS:'GET_MOVIES_SUCCESS',
    GET_MOVIES_FAIL:'GET_MOVIES_FAI'
}
export const seatTypes={
    SEAT_INFO:'SEAT_INFO',
    SEAT_ALLOCATION:'SEAT_ALLOCATION',
    BOOKING:'BOOKING'
}